---
###############################################################################
# Role Metadata
###############################################################################
# worker-join has no dependencies
# This role can be called independently

dependencies: []
